title: Arnault Chatelain
description: |
  PhD candidate in Economics\n
  Computational Social Scientist\n
  Python enthusiast


#Slate theme
remote_theme: pages-themes/slate@v0.2.0

#Links in header
baseurl: ""
url: "https://archatelain.github.io"

# Navigation links
navigation:
  - name: "Home"
    url: "index.html"
  - name: "Research"
    url: "research.html"
  - name: "Teaching/Talks"
    url: "teaching.html"
  - name: "Programming"
    url: "programming.html"
  - name: "CV"
    url: "CV.html"
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"